### ISSUE TITLE
Handle slow stream inputs

### ISSUE THREAD

**Issue by cryogenian** [precog/quasar-destination-snowflake#249]
+ Create a transactor per staging file
+ Split input byte stream by size _and_ idle time, i.e. if there is no data for 10min, end current stream
+ Write streams to temp files, emit them on inner stream end.
+ Upload these temp files removing them when upload succeded, retry on temp files too.

This way SF connection won't wait, but immediately upload stagin files, also much less memory will be consumed. The drawback is that it will take more time, IIUC the time is equal to maximum time one file is uploaded to staging. Which is not that bad especially for slow datasets.

**Comment by cryogenian** [comment]
<3>

**Comment by cryogenian** [comment]
https://github.com/precog/features/issues/63

**Comment by jsantos17** [comment]
Not sure if I'm understanding this correctly, but you can configure Hikari to renew the connections in the pool for you using the `maxLifetime` parameter when initializing the pool. So connections are kept alive for you.

You need to be careful to avoid checking out connections for too long, but each time you checkout a connection from the pool it's guaranteed to be alive.

**Comment by cryogenian** [comment]
Right, but `keep alive` is set to `true` already. I suspect that the problem happens during staging for some reason (it's not really unexpected anyone could forget about this). So, to actually fix I'm thinking about caching the data in the disk and upload it file be file, that will help us with memory usage too (yay 🎉 )

**Comment by cryogenian** [comment]
<1>

**Comment by cryogenian** [comment]
<0>
